---
- name: restart freeradius
  ansible.builtin.systemd:
    name: freeradius
    state: restarted

- name: restart control
  ansible.builtin.systemd:
    name: control
    state: restarted
    daemon_reload: true
